apiVersion: apps/v1
kind: Deployment

metadata:
  name: apptodo-deployment
  labels:
    app: todoapp1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp1
  template:
    metadata:
      labels:
        app: todoapp1
    spec:
      imagePullSecrets: 
        - name: docker-hub-secret created 
      containers:
      - name: todoapp1
        image: indranivaishnavi1809/todoapp:python-app-hub
        ports:
          - containerPort: 8000
